- hosts: all
  become: yes
  gather_facts: false
  vars:
  
  tasks:
  - name: Creating an empty file
    file:
      path: "/etc/docker/daemon.json"
      state: touch
      mode: 0755
  
  - name: load var from file
    slurp:
      src: /etc/docker/daemon.json
    register: docker_vars

  - debug:
      msg: "{{ docker_vars.content|b64decode|from_json }}"

  - name: append more key/values
    set_fact:
      docker_vars: "{{ docker_vars.content|b64decode|from_json }}"

  - name: append more key/values
    set_fact:
      docker_vars: "{{ docker_vars | default([]) | combine({ item.key : item.value }) }}"
    with_items:
    - { key: "exec-opts", value: [ "native.cgroupdriver=systemd" ] }
    - { key: "registry-mirrors", value: [ "http://docker-cache.grid5000.fr" ] }

  - debug:
      var: docker_vars

  - name: write var to file
    copy:
      content: "{{ docker_vars | to_nice_json }}"
      dest: /etc/docker/daemon.json
