- hosts: all
  become: yes
  tasks:
  - name: Remove swapfile from /etc/fstab
    mount:
      name: swap
      fstype: swap
      state: absent

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: set up authorized keys for root user
    authorized_key: user=root key="{{item}}"
    with_file:
      - ~/.ssh/id_rsa.pub

  - name: Assign inventory name to unconfigured hostnames (non-CoreOS, Suse and ClearLinux)
    hostname:
      name: "{{ inventory_hostname }}"

  - name: "Add IP address of all hosts to all hosts"
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"

  - name: install remote apt deps
    apt:
      name: "{{ item }}"
      state: present
    with_items:
     - apt-transport-https
     - ca-certificates
     - gnupg2
     - software-properties-common

  - name: add Docker apt-key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

  - name: add Docker's APT repository
    apt_repository:
     repo: deb https://download.docker.com/linux/ubuntu focal stable
     state: present
     filename: 'docker'

  - name: install docker-ce
    apt:
     name: docker-ce
     state: present
     update_cache: true

  - name: install containerd.io
    apt:
     name: containerd.io
     state: present
     update_cache: true

  - name: install docker-ce-cli
    apt:
     name: docker-ce-cli
     state: present
     update_cache: true

  - name: Copy from Local to Remote Target Machine with 'copy'
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json
      backup: yes

  - name: restart service cron on centos, in all cases, also issue daemon-reload to pick up config changes
    systemd:
      state: restarted
      daemon_reload: yes
      name: docker

  - name: add Kubernetes apt-key
    apt_key:
     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
     state: present

  - name: add Kubernetes' APT repository
    apt_repository:
     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: 'kubernetes'

  - name: install kubelet
    apt:
     name: kubelet=1.23.3-00
     state: present
     update_cache: true

  - name: install kubeadm
    apt:
     name: kubeadm=1.23.3-00
     state: present

- hosts: all[0]
  become: yes
  tasks:
   - name: install kubectl
     apt:
       name: kubectl=1.23.0-00
       state: present
       force: yes