- hosts: all
  become: yes
  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: install remote apt deps
    apt:
      name: "{{ item }}"
      state: present
    with_items:
     - apt-transport-https
     - ca-certificates
     - gnupg2
     - curl
     - software-properties-common
     - vim

  # - name: add Docker apt-key
  #   apt_key:
  #    url: https://download.docker.com/linux/ubuntu/gpg
  #    state: present

  # - name: add Docker's APT repository
  #   apt_repository:
  #    repo: deb https://download.docker.com/linux/ubuntu focal stable
  #    state: present
  #    filename: 'docker'

  # - name: install Docker
  #   apt:
  #    name: docker-ce
  #    state: present
  #    update_cache: true

  # - name: install docker-ce-cli
  #   apt:
  #    name: docker-ce-cli
  #    state: present
  #    update_cache: true

  # - name: install containerd.io
  #   apt:
  #    name: containerd.io
  #    state: present
  #    update_cache: true

  # - name: Copy daemon.json from Local to all node
  #   copy:
  #     src: daemon.json
  #     dest: /etc/docker/daemon.json
  #     backup: yes

  # - name: restart service docker
  #   systemd:
  #     state: restarted
  #     daemon_reload: yes
  #     name: docker

  - name: add Kubernetes apt-key
    apt_key:
     url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
     state: present

  - name: add Kubernetes' APT repository
    apt_repository:
     repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
     state: present
     filename: 'kubernetes'

  - name: install kubelet
    apt:
     name: kubelet=1.27.3-00
     state: present
     update_cache: true

  - name: install kubeadm
    apt:
     name: kubeadm=1.27.3-00
     state: present

  - name: install kubectl
    apt:
     name: kubectl=1.27.3-00
     state: present
     force: yes