python3 ./delcluster/management.py
python3 ./delcluster/m1.py
python3 ./delcluster/m2.py
python3 ./delcluster/m3.py
python3 ./delcluster/m4.py
python3 ./delcluster/m5.py
python3 ./delcluster/m6.py
python3 ./delcluster/m7.py
python3 ./delcluster/m8.py
python3 ./delcluster/m9.py
python3 ./delcluster/m10.py
python3 ./delcluster/m11.py
python3 ./delcluster/m12.py
python3 ./delcluster/m13.py
python3 ./delcluster/m14.py
python3 ./delcluster/m15.py
python3 ./delcluster/m16.py
python3 ./delcluster/m17.py
python3 ./delcluster/m18.py
python3 ./delcluster/m19.py
python3 ./delcluster/m20.py
python3 ./delcluster/m21.py
python3 ./delcluster/m22.py
python3 ./delcluster/m23.py
python3 ./delcluster/m24.py
python3 ./delcluster/m25.py
python3 ./delcluster/m26.py
python3 ./delcluster/m27.py
python3 ./delcluster/m28.py
python3 ./delcluster/m29.py
python3 ./delcluster/m30.py
python3 ./delcluster/m31.py
python3 ./delcluster/m32.py
python3 ./delcluster/m33.py
python3 ./delcluster/m34.py
python3 ./delcluster/m35.py
python3 ./delcluster/m36.py
python3 ./delcluster/m37.py
python3 ./delcluster/m38.py
python3 ./delcluster/m39.py
python3 ./delcluster/m40.py